apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/* #Tempat file yaml/config for kubernetes
build:
  local:
    push: false
  # googleCloudBuild:
  #   projectId: ticketing-dev-365413
  artifacts:
    # - image: us.gcr.io/ticketing-dev-365413/auth #image env in GCP clod service kubernetes
    - image: fajarcahyadi/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: fajarcahyadi/client #image env in GCP clod service kubernetes
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
    - image: fajarcahyadi/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: fajarcahyadi/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: fajarcahyadi/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: fajarcahyadi/payment
      context: payment
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
