name: deploy-manifests

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}
  
on:
  push:
    branches:
      - master
    paths:
      - 'infra/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
        with:
          credentials_json: '${{ secrets.CREDENTIALS_JSON }}'
      - run: |-
          gcloud --quite auth configure-docker
      - uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
        with:
          cluster_name: $GKE_CLUSTER
          location: $GKE_ZONE
          credentials_json: '${{ secrets.CREDENTIALS_JSON }}'
      - run: kubectl apply -f infra/k8s && kubectl -f apply infra/k8f-prod
