name: deploy-orders

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

on:
  push:
    branches:
      - master
    paths:
      - "orders/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd orders && docker build -t fajarcahyadi/orders .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run: docker push fajarcahyadi/orders
      - uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.CREDENTIALS_JSON }}"
      - run: |-
          gcloud --quiet auth configure-docker
      - uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: "ticketing-dev"
          location: "asia-southeast1-a"
      - run: kubectl rollout restart deployment orders-depl
